In [2]:
import torch

Tensor

In [3]:
# param is size
# 1D
x = torch.empty(3)
# 2D
y = torch.empty(3,2)
# 3D
z = torch.empty(3,3,3)
print(x)
print(y)
print(z)

tensor([0., 0., 0.])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [8.9633e-33, 4.7562e+30, 9.2860e-04]],

        [[7.5031e+28, 6.2618e+22, 4.7428e+30],
         [2.9514e+29, 1.8037e+28, 8.6468e-01],
         [4.5144e+27, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [4]:
# Random
x = torch.rand(2,2)
print(x)
# Zeros
x = torch.zeros(2,2)
print(x)
# Ones
x = torch.ones(2,2)
print(x)

tensor([[0.6971, 0.7141],
        [0.2155, 0.6328]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [5]:
# Check data type
print(x.dtype)
# Specify data type
x = torch.ones(2,2,dtype=torch.int)
print(x.dtype)
# size
print(x.size())

torch.float32
torch.int32
torch.Size([2, 2])


In [6]:
# Creating tensor from lists 
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


Tensor Operations

In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.9280, 0.8099],
        [0.7316, 0.5522]])
tensor([[0.0753, 0.8483],
        [0.8375, 0.5096]])


Basic Arithmetic Operations

In [8]:
# Element wise addition
z = x + y
print(z)
z = torch.add(x,y)
print(z)

tensor([[1.0033, 1.6582],
        [1.5692, 1.0618]])
tensor([[1.0033, 1.6582],
        [1.5692, 1.0618]])


In [9]:
# Inplace addition
# in pytorch trailing _ means inplace operations
y.add_(x)
print(y)

tensor([[1.0033, 1.6582],
        [1.5692, 1.0618]])


In [10]:
# Element wise subtraction
z = x - y
print(z)
z = torch.sub(x,y)
print(z)

tensor([[-0.0753, -0.8483],
        [-0.8375, -0.5096]])
tensor([[-0.0753, -0.8483],
        [-0.8375, -0.5096]])


In [11]:
# Element wise multiplication
z = x * y
print(z)
z = torch.mul(x,y)
print(z)

tensor([[0.9311, 1.3430],
        [1.1480, 0.5864]])
tensor([[0.9311, 1.3430],
        [1.1480, 0.5864]])


In [12]:
# Element wise division
z = x / y
print(z)
z = torch.div(x,y)
print(z)

tensor([[0.9250, 0.4884],
        [0.4662, 0.5201]])
tensor([[0.9250, 0.4884],
        [0.4662, 0.5201]])


Slicing Operations

In [13]:
x = torch.rand(5,3)
print(x)
# All rows and 1st column i-e 1st column of matrix
print(x[:,0])
# row 1 and all column i-e 2nd row of matrix
print(x[1,:])
# value at 1,1 positon
print(x[1,1]) # This returns a tensor
print(x[1,1].item()) # This returns a value if a single value is in tensor

tensor([[0.2684, 0.2170, 0.7452],
        [0.3298, 0.1474, 0.7473],
        [0.2677, 0.3688, 0.6479],
        [0.0950, 0.8245, 0.2827],
        [0.1686, 0.6487, 0.7858]])
tensor([0.2684, 0.3298, 0.2677, 0.0950, 0.1686])
tensor([0.3298, 0.1474, 0.7473])
tensor(0.1474)
0.1473594307899475


Reshaping

In [14]:
x = torch.rand(4,4)
print(x)
print(x.size())
# converting to 1D from 2D
y = x.view(16)
print(y)
print(y.size())
# If -1 is used pytorch will automatically determine the dimension
y = x.view(-1,8)
print(y)
print(y.size())

tensor([[0.0774, 0.8861, 0.1863, 0.9873],
        [0.9181, 0.7235, 0.7341, 0.9848],
        [0.9756, 0.5280, 0.7638, 0.1453],
        [0.8292, 0.0211, 0.2250, 0.2507]])
torch.Size([4, 4])
tensor([0.0774, 0.8861, 0.1863, 0.9873, 0.9181, 0.7235, 0.7341, 0.9848, 0.9756,
        0.5280, 0.7638, 0.1453, 0.8292, 0.0211, 0.2250, 0.2507])
torch.Size([16])
tensor([[0.0774, 0.8861, 0.1863, 0.9873, 0.9181, 0.7235, 0.7341, 0.9848],
        [0.9756, 0.5280, 0.7638, 0.1453, 0.8292, 0.0211, 0.2250, 0.2507]])
torch.Size([2, 8])


Converting From/To Numpy

In [15]:
import numpy as np

Convert from tensor to numpy

In [16]:
a = torch.ones(5)
print(a)
print(type(a))
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


**Note**: Here if both tensor and numpy array are in CPU then both of them will share same memory location so changing one variable will affect another and vice versa.

In [17]:
a.add_(1)
print(a)
# Here we can see than b is also changed when a was changed
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Convert from numpy to tensor

In [18]:
a = np.ones(5)
print(a,type(a))
b = torch.from_numpy(a)
print(b,type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [19]:
# Also in this case both share same location in memory
a += 5
print(a)
print(b) 

[6. 6. 6. 6. 6.]
tensor([6., 6., 6., 6., 6.], dtype=torch.float64)


Check if cuda is available to run tensors in GPU  
Also GPU tensors cannot be converted back to numpy

In [20]:
torch.cuda.is_available()

False

## Autograd
- It is used to calculate gradients in pytorch

In [21]:
# This parameter is kept to true when we need to calculate gradients
x = torch.randn(3,requires_grad=True)
print(x)

tensor([-1.2260, -0.5951, -0.6820], requires_grad=True)


When we perform operations on such tensors we can see a grad_fn parameter

In [22]:
y = x + 2
print(y) 

tensor([0.7740, 1.4049, 1.3180], grad_fn=<AddBackward0>)


In [27]:
z = y*y*2
print(z)
# this calculates gradient
# * For a vector variable z we need to pass a gradient argument by creating vector of same size 
v = torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v) #dz/dx
# To print the calculated gradients
print(x.grad) 

tensor([1.1980, 3.9473, 3.4742], grad_fn=<MulBackward0>)
tensor([-2.4541,  4.1482, -1.8329])


Calculating gradient

In [25]:
z = z.mean()
print(z)
# this calculates gradient
# * For a scalar variable z we don't need to send another parameter in the backward function
z.backward() #dz/dx
# To print the calculated gradients
print(x.grad) 

tensor(2.8732, grad_fn=<MeanBackward0>)
tensor([1.0319, 1.8731, 1.7573])


Removing require grad attribute

In [30]:
x = torch.randn(3,requires_grad=True)
print(x)
# * 3 methods
# x.requires_grad_(False)
x.requires_grad_(False)
print(x)
x.requires_grad_(True)
# x.detach()
y = x.detach()
print(y)
# with torch.no_grad():
y=x+2
print(y)
with torch.no_grad():
    y=x+2
    print(y)

tensor([0.7310, 0.6867, 0.5042], requires_grad=True)
tensor([0.7310, 0.6867, 0.5042])
tensor([0.7310, 0.6867, 0.5042])
tensor([2.7310, 2.6867, 2.5042], grad_fn=<AddBackward0>)
tensor([2.7310, 2.6867, 2.5042])


Here the gradients will be accumulated in the grad attribute of the tensor, so we may need to reset the grad attribute in case of multiple iterations

In [32]:
weights = torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_output = (weights+3).sum()
    model_output.backward()
    print(weights.grad)
    # to reset the gradients in every iteration
    weights.grad.zero_()

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])


## Backpropagation

For each operation we perform pytorch creates a computational graph

In [35]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

# weights
w = torch.tensor(1.0,requires_grad=True)
print(w)

# forward pass and compute the loss
y_hat = w*x
loss = (y_hat-y)**2

print(loss)

# backward pass
loss.backward()
print(w.grad)

# update weights
w = w + w.grad 
print(w)
# next forward and backward pass


tensor(1., requires_grad=True)
tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
tensor(-1., grad_fn=<AddBackward0>)


## Gradient Descent

Manual Way using numpy

In [38]:
# f = w*x 
X = np.array([1,2,3,4],dtype=np.float32)
Y = np.array([2,4,6,8],dtype=np.float32)

w = 0.0

# model prediction
def forward(x):
    return w*x

# loss = MSE
def loss(y,y_predicted):
    return ((y_predicted-y)**2).mean()

# gradient
# MSE(e) = 1/N * (w*x -y)**2 
# de/dw =  1/N * 2x*(w*x-y)
def gradient(x,y,y_predicted):
    return np.dot(2*x,y_predicted-y).mean()

print(f'Prediction before training:  f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # prediction = forward pass 
    y_pred = forward(X)
    # loss
    l = loss(Y,y_pred)
    # gradients 
    dw = gradient(X, Y, y_pred)
    # update weights
    w -= learning_rate*dw 

    if epoch%1 == 0:
        print(f'epoch {epoch+1}: w={w:.3f}, loss = {l:.8f}')

print(f'Prediction after training:  f(5) = {forward(5):.3f}')

Prediction before training:  f(5) = 0.000
epoch 1: w=1.200, loss = 30.00000000
epoch 2: w=1.680, loss = 4.79999924
epoch 3: w=1.872, loss = 0.76800019
epoch 4: w=1.949, loss = 0.12288000
epoch 5: w=1.980, loss = 0.01966083
epoch 6: w=1.992, loss = 0.00314574
epoch 7: w=1.997, loss = 0.00050331
epoch 8: w=1.999, loss = 0.00008053
epoch 9: w=1.999, loss = 0.00001288
epoch 10: w=2.000, loss = 0.00000206
epoch 11: w=2.000, loss = 0.00000033
epoch 12: w=2.000, loss = 0.00000005
epoch 13: w=2.000, loss = 0.00000001
epoch 14: w=2.000, loss = 0.00000000
epoch 15: w=2.000, loss = 0.00000000
epoch 16: w=2.000, loss = 0.00000000
epoch 17: w=2.000, loss = 0.00000000
epoch 18: w=2.000, loss = 0.00000000
epoch 19: w=2.000, loss = 0.00000000
epoch 20: w=2.000, loss = 0.00000000
Prediction after training:  f(5) = 10.000


Automatic way using pytorch

In [43]:
# f = w*x 
X = torch.tensor([1,2,3,4],dtype=torch.float32)
Y = torch.tensor([2,4,6,8],dtype=torch.float32)

w = torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

# model prediction
def forward(x):
    return w*x

# loss = MSE
def loss(y,y_predicted):
    return ((y_predicted-y)**2).mean()

# gradient will be using pytorch

print(f'Prediction before training:  f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # prediction = forward pass 
    y_pred = forward(X)
    # loss
    l = loss(Y,y_pred)
    # gradients = backward pass
    l.backward() #dl/dx
    # update weights
    with torch.no_grad():
        w -= learning_rate*w.grad
    
    # zero gradients
    w.grad.zero_()

    if epoch%10 == 0:
        print(f'epoch {epoch+1}: w={w:.3f}, loss = {l:.8f}')

print(f'Prediction after training:  f(5) = {forward(5):.3f}')

Prediction before training:  f(5) = 0.000
epoch 1: w=0.300, loss = 30.00000000
epoch 11: w=1.665, loss = 1.16278565
epoch 21: w=1.934, loss = 0.04506890
epoch 31: w=1.987, loss = 0.00174685
epoch 41: w=1.997, loss = 0.00006770
epoch 51: w=1.999, loss = 0.00000262
epoch 61: w=2.000, loss = 0.00000010
epoch 71: w=2.000, loss = 0.00000000
epoch 81: w=2.000, loss = 0.00000000
epoch 91: w=2.000, loss = 0.00000000
Prediction after training:  f(5) = 10.000


Using pytorch functions for loss and optimization instead of custom fuctions

In [44]:
import torch.nn as nn 
# f = w*x 
X = torch.tensor([1,2,3,4],dtype=torch.float32)
Y = torch.tensor([2,4,6,8],dtype=torch.float32)

w = torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

# model prediction
def forward(x):
    return w*x


# gradient will be using pytorch

print(f'Prediction before training:  f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 100

# loss provided by pytorch
loss = nn.MSELoss()
# SGD => Stochastic Gradient Descent
optimizer = torch.optim.SGD([w],lr=learning_rate)

for epoch in range(n_iters):
    # prediction = forward pass 
    y_pred = forward(X)
    # loss
    l = loss(Y,y_pred)
    # gradients = backward pass
    l.backward() #dl/dx
    # update weights
    # no need to manually update weights
    optimizer.step()
    
    # zero gradients
    optimizer.zero_grad()

    if epoch%10 == 0:
        print(f'epoch {epoch+1}: w={w:.3f}, loss = {l:.8f}')

print(f'Prediction after training:  f(5) = {forward(5):.3f}')

Prediction before training:  f(5) = 0.000
epoch 1: w=0.300, loss = 30.00000000
epoch 11: w=1.665, loss = 1.16278565
epoch 21: w=1.934, loss = 0.04506890
epoch 31: w=1.987, loss = 0.00174685
epoch 41: w=1.997, loss = 0.00006770
epoch 51: w=1.999, loss = 0.00000262
epoch 61: w=2.000, loss = 0.00000010
epoch 71: w=2.000, loss = 0.00000000
epoch 81: w=2.000, loss = 0.00000000
epoch 91: w=2.000, loss = 0.00000000
Prediction after training:  f(5) = 10.000


Using Pytorch model to replace manually implemented forward pass function

In [46]:
import torch.nn as nn 
# f = w*x 
X = torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
Y = torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)

# test tensor for prediction
X_test = torch.tensor([5],dtype=torch.float32)

n_samples, n_features = X.shape

input_size = n_features
output_size = n_features

# model prediction
model = nn.Linear(in_features=input_size, out_features=output_size)

# for multi layer model
class LinearRegression(nn.Module):
    def __init__(self,input_dim,output_dim):
        super(LinearRegression, self).__init__()
        # define layers
        self.lin = nn.Linear(input_dim,output_dim)
    
    def forward(self,x):
        return self.lin(x)

model = LinearRegression(input_size, output_size)

# gradient will be using pytorch

print(f'Prediction before training:  f(5) = {model(X_test).item():.3f}')

# Training
learning_rate = 0.01
n_iters = 100

# loss provided by pytorch
loss = nn.MSELoss()
# SGD => Stochastic Gradient Descent
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(n_iters):
    # prediction = forward pass 
    y_pred = model(X)
    # loss
    l = loss(Y,y_pred)
    # gradients = backward pass
    l.backward() #dl/dx
    # update weights
    # no need to manually update weights
    optimizer.step()
    
    # zero gradients
    optimizer.zero_grad()

    if epoch%10 == 0:
        [w,b] = model.parameters()
        print(f'epoch {epoch+1}: w={w[0][0].item():.3f}, loss = {l:.8f}')

print(f'Prediction after training:  f(5) = {model(X_test).item():.3f}')

Prediction before training:  f(5) = -0.184
epoch 1: w=0.327, loss = 32.22016144
epoch 11: w=1.631, loss = 0.85408729
epoch 21: w=1.843, loss = 0.04138092
epoch 31: w=1.880, loss = 0.01923186
epoch 41: w=1.889, loss = 0.01760177
epoch 51: w=1.893, loss = 0.01656403
epoch 61: w=1.896, loss = 0.01559958
epoch 71: w=1.899, loss = 0.01469158
epoch 81: w=1.902, loss = 0.01383645
epoch 91: w=1.905, loss = 0.01303109
Prediction after training:  f(5) = 9.810
